name: OFOX

on:
  push:
    tags:
      - 'OFOX-v*'

  workflow_dispatch:

jobs:

  ofox:
    runs-on: ubuntu-latest

    env:
      E6746_OUT_DIR: /home/runner/ofox/out/target/product/E6746

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean up
        uses: rokibhasansagar/slimhub_actions@main

      - name: setting_up
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          mkdir -p /home/runner/bin
          mkdir -p /home/runner/ofox
          mkdir -p /home/runner/ofox-scripts
          mkdir -p /home/runner/venv
          sudo apt update
          sudo apt install python3 python2 virtualenv
          cd /home/runner/ofox-scripts
          sudo apt install git aria2 -y
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd /home/runner/ofox-scripts/scripts
          sudo bash setup/android_build_env.sh
          sudo bash setup/install_android_sdk.sh
          cd /home/runner
          virtualenv --python=$(which python2) /home/runner/venv

      - name: downloading sources and setting up device tree
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          cd /home/runner/ofox-scripts
          git clone https://gitlab.com/OrangeFox/sync.git
          cd /home/runner/ofox-scripts/sync
          chmod +x *.sh
          ./get_fox_10.sh /home/runner/ofox
          mkdir -p /home/runner/ofox/device/micromax
          cd /home/runner/ofox/device/micromax
          git clone https://github.com/nit-in/device_micromax_E6746.git -b ofox E6746
          
      - name: build recovery
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          cd /home/runner/ofox
          touch /home/runner/pbrp/device/micromax/E6746/vendorsetup.sh
          echo "add_lunch_combo omni_E6746-eng" > /home/runner/pbrp/device/micromax/E6746/vendorsetup.sh
          source /home/runner/venv/bin/activate
          python --version
          source build/envsetup.sh
          lunch omni_E6746-eng
          mka adbd recoveryimage ALLOW_MISSING_DEPENDENCIES=true FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1 LC_ALL="C"
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.E6746_OUT_DIR }}/recovery.img, ${{ env.E6746_OUT_DIR }}/*.zip"
          token: ${{ secrets.RECOVERY }}

